### ISSUE TITLE
Would be great: Resizable Global Search window & remembering result grid column widths

### ISSUE THREAD

**Issue by schittli** [Rookiestyle/GlobalSearch#15]
Hello

**Thank you very much for sharing your great work!**

## Summary
I have a usability feature request: it would be great if:
* we could resize the Global Search Window 
* and if Global Search remembers the last window size 😃 
* Global Search would remember the result grid column widths

## Added value
* The Global Search Windows is often too small and then, one has to use scrollbars 
* If the Window is resizable, then one can just click the right record
* The Global Search result grid columns are usually wrong, so that one has to resize them.
* If the column widths are just right, then the user can just click to the right record

## Example
N/A

**Comment by Rookiestyle** [comment]
I'm working on a resizable result window for GlobalSearch.

It will allow to change window size and column widths.
Window size, window position and column widths will be remembered

**Comment by schittli** [comment]
Thank you very much, @Rookiestyle, for taking on this task!

**Comment by Rookiestyle** [comment]
Implemented with ce4d9581479a69e44b168fec1e47197202b21265 and 43860fee0a1a58c1de4f8ab5eadbdcc7df37a0fd

New release v1.1 published
