### ISSUE TITLE
Incompatibilites with upcoming release

### ISSUE THREAD

**Issue by TBugReporter** [Rookiestyle/GlobalSearch#16]
Cross reference:
https://sourceforge.net/p/keepass/feature-requests/1294/?limit=250#e8a2/3524

**Comment by Rookiestyle** [comment]
Working on it

**Comment by Rookiestyle** [comment]
Will wait for Dominik to finalize the implementation in his upcoming release of KeePass as mentioned in above cross reference

**Comment by Rookiestyle** [comment]
Next version of KeePass does not require a change of GlobalSearch
