### ISSUE TITLE
Search Window Column Widths

### ISSUE THREAD

**Issue by trenddeko** [Rookiestyle/GlobalSearch#17]
First of all, I would like to thank you very much for the great plugin. It is fantastic.

Something I've been wishing for a long time is that the columns in the popup are so wide that the entries are completely visible. As you can see in the screnshot, all the entries are truncated in width.

For me there would be several options to do this:
1.) the width of the popup window can be adjusted.
2) the popup does an autoresize so that all columns have an autowidth
3) it is possible to simply not show some columns

If it would be possible to implement one of the three variants, that would be excellent!

I would be very happy about a feedback.

Greetings Michael
![keepass search popup](https://user-images.githubusercontent.com/121336112/209427973-be992da1-018a-4563-89e5-7d2f56d4fce8.png)

**Comment by Rookiestyle** [comment]
Which version are you using?

The result window's size can be changed since v1.1.

Changing column widths is also possible.
Move your cursor to the column header dividers marked in red for that.
Cursor should change and you should be able to drag the column width
![image](https://user-images.githubusercontent.com/36454520/209441739-750b7a7c-eab2-424d-9838-3a354c0d8ad6.png)

**Comment by trenddeko** [comment]
Hello
thank you for your answer. I use version 2.49. What you describe is possible. However, I have to do it every time I use the search function. It would be much more convenient if the column widths would automatically have the full width and the values would be displayed completely.

I look forward to your feedback and continue to wish you a Merry Christmas.

Michael

**Comment by Rookiestyle** [comment]
I'm trying to implement the following:

- [x] Search result shows the same columns as the entry list
- [x] Column widths will be set to the same widths as in the entry list
- [x] Keep possibility to change column widths 

This will **only** apply for the search started by `Find...`
Other searches like `Find -> Expired`, ... will not be affected by that and continue to use the standard columns and column widths implemented by KeePass itself.

The size of the window showing the search results will not be changed automatically, if neccessary the will be a scrollbar within the listview containng the found entries.
You will still be able to change window size and position and my plugin will remember that.
