### ISSUE TITLE
doesn't play well with KeeResize

### ISSUE THREAD

**Issue by TBugReporter** [Rookiestyle/GlobalSearch#20]
## Overview
With KeeResize and GlobalSearch both installed, the Find window is slightly off in terms of size.  (See [image here](https://sourceforge.net/u/t_bugreporter/wiki/glsch/).)

## Context
[NOTE]: # (Provide any additional information you may have)
OS:   Win11
KeePass Version:  2.57
Plugin Version: 1.31

**Comment by TBugReporter** [comment]
It's getting worse...

Original:
![Screenshot 2024-06-19 010823](https://github.com/Rookiestyle/GlobalSearch/assets/16196686/8d8fe23e-ebe5-4b4b-8162-94dbb28b4ef1)
Latest:
![Screenshot 2024-07-04 035209](https://github.com/Rookiestyle/GlobalSearch/assets/16196686/1f045630-43c3-4095-a50b-9725ef96e61c)
(Also note that nothing I do brings your added option or the bottom buttons into full view; I have to cope with just a sliver of the checkbox showing - or use the Tab key to move to it and Space to toggle it.)

**Comment by Rookiestyle** [comment]
Try the attached debug build.

It was pretty complex to deal all 3 cases
* No KeeResize
* KeeResize demo version
* KeeResize full version

[GlobalSearch.zip](https://github.com/user-attachments/files/16102238/GlobalSearch.zip)

**Comment by TBugReporter** [comment]
Your new version seems to always add 100 to the window height, regardless of whether it needs it or not - the first time I did Ctrl-F, the new section was nicely framed in the window (despite it being larger than necessary), but the second time the window grew again, unnecessarily.

**Comment by Rookiestyle** [comment]
"second time" = Closing and opening the search window again? Does it grow bigger everytime or only the second time and then sticks to this new size? 

Please try the new version, I once again changed it a bit and added some info messages
[GlobalSearch.zip](https://github.com/user-attachments/files/16115263/GlobalSearch.zip)

**Comment by TBugReporter** [comment]
> Closing and opening the search window again?

Yes.
> Does it grow bigger everytime [...] ?

Yes.

After manually shrinking to fit the screen:
![Screenshot 2024-07-06 221049](https://github.com/Rookiestyle/GlobalSearch/assets/16196686/3f0099c5-34f1-41d8-b5e9-29a48e2512cd)
After close and immediate reopen:
![Screenshot 2024-07-06 221141](https://github.com/Rookiestyle/GlobalSearch/assets/16196686/1af82e0b-f3bc-40fb-b387-f894626ad9ca)
Those were with 1.3.1.1; this next one is 1.3.1.2:
![Screenshot 2024-07-06 224643](https://github.com/Rookiestyle/GlobalSearch/assets/16196686/c1749820-0d90-47b9-b544-a1056e403de7)
And yes, KeeResize is still installed.

**Comment by TBugReporter** [comment]
After "OK":
![Screenshot 2024-07-06 230739](https://github.com/Rookiestyle/GlobalSearch/assets/16196686/f19369ac-8dbe-48a8-963e-330772b6167e)

**Comment by Rookiestyle** [comment]
https://github.com/Rookiestyle/GlobalSearch/wiki/Create-a-debugfile

I need to know which plugins I can detect

**Comment by Rookiestyle** [comment]
One more try...
This version 1.3.1.3 comes with different adjustments and active debug mode.

If it works, an "OK" is sufficient, I'll publish a new release then - without active debug flag
If it does not work, please attach the created debug file.
[GlobalSearch.zip](https://github.com/user-attachments/files/16119755/GlobalSearch.zip)

**Comment by TBugReporter** [comment]
Size is now stable, but search itself crashes.  It works - I get results, but only after "Continue"ing from an unhandled exception.
![Screenshot 2024-07-08 020848](https://github.com/Rookiestyle/GlobalSearch/assets/16196686/749ca8e3-134c-450e-a430-c9c5766f7613)
BTW, is the checkbox supposed to clear between every search?
[Debug_GlobalSearch_20240708T055544Z.xml.txt](https://github.com/user-attachments/files/16123489/Debug_GlobalSearch_20240708T055544Z.xml.txt)

**Comment by Rookiestyle** [comment]
The checkbox will remember its previous state.
This did not happen as concequence of the uncaught exception.

The newly released version 1.3.2 contains the KeeResize adjustment and the fix of this exception
