### ISSUE TITLE
Minor typo on GitHub homepage for this plugin

### ISSUE THREAD

**Issue by TBugReporter** [Rookiestyle/GlobalSearch#7]
While downloading the new version I noticed that under "Configuration", it says:

> GlobalSearch will perform a search in all open databases if both criteria are met:
> 
> - More then[sic] one database is opened
> - The corresponding option in GlobalSearch's configuration is active

I would think you should have "th*a*n" here.

**Comment by Rookiestyle** [comment]
You're absolutely right, thanks
