### ISSUE TITLE
Quick search does not work

### ISSUE THREAD

**Issue by auanasgheps** [Rookiestyle/GlobalSearch#8]
## Overview
Hi,
I've installed the plugin and quick search box does not work as expected: does not find entries from the other DB
I am referring to the box you see here:
![image](https://user-images.githubusercontent.com/20586878/106478638-ae36a700-64a9-11eb-9f6c-a18767b6e2d8.png)

Standard search does work (CTRL+F) but to the honest I never use it.
Is this expected behaviour?

## Steps to Reproduce
1. Install the plugin
2. Open two DB
3. Use the quick search box to search an entry in the second DB
4. Results are not displayed

## Expected Behavior
Search in all databased

## Actual Behavior
Only searches in current DB

## Context
[NOTE]: # (Provide any additional information you may have)
OS: Windows 10 2004
KeePass Version: 2.47
Plugin Version: 0.7.2

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)

**Comment by Rookiestyle** [comment]
> Currently covered search functions:
Find... (who would have thought that...)
Last Modified Entries
Large Entries
Duplicate Passwords
Similar Passwords (Pairs)...
Similar Passwords (Clusters)...
Password Quality...
Expired entries

Quicksearch is working completely different internally and difficult to hook into.
I'll have a look and if it's possible with reasonable efforts, I'll add this functionality.
Meanwhile... [Ctrl] + [F] is only two keys away ;)

**Comment by Rookiestyle** [comment]
Unfortunately the only options is to replace the built-in quicksearch functionality by something completely different.
This would result in constant effort to to keep the plugin's version of quicksearch consistent with the KeePass way of doing a quicksearch and will be additionally complex as multiple KeePass versions can be used by different users.

I will close this for now and reopen it once KeePass will seperate doing a quicksearch from displaying this quicksearch's result.

**Comment by auanasgheps** [comment]
Thanks for looking into this!
